<?php

namespace Modules\User\Service\User;

use App\Helpers\FileHelper;
use App\Service\BaseService;
use Modules\User\Models\UserSocialModel;

class UserSocialService extends BaseService {

    public static $modelClass = UserSocialModel::class;

    protected function init($model){
        return $model;
    }

    public function setUser($model){
        $this->setForeignKey('user_id', 'user', $model);
        return $this;
    }

    public function setType($value){
        $this->setFields('type',$value);
        return $this;
    }
    public function setOpenId($value){
        $this->setFields('open_id',$value);
        return $this;
    }
    public function setUnionId($value){
        $this->setFields('unionid',$value);
        return $this;
    }
    public function setResultJson($value){
        $this->setFields('result_json',$value);
        return $this;
    }
    
    public function setGender($gender){
        $this->model->gender = $gender;
        return $this;
    }

    public function setNickname($nickname){
        $this->model->nickname = $nickname;
        return $this;
    }
    
    public function setAvatar($avatar){
        $this->model->avatar = $avatar;
        return $this;
    }

    public function saved() {
        // 完善用户头像
        if ($this->model->user){
            if (empty($this->model->user->avatar)){
                $service = new UserService($this->model->user);
                $service->setAvatar(FileHelper::downloadImage($this->model->avatar, FileHelper::$nameSpaceAvatar));
                $service->save();
            }
        }
        return parent::saved(); // TODO: Change the autogenerated stub
    }
}