<?php

namespace Modules\User\Http\Resources\Admin;



use Modules\User\Http\Resources\Base\UserBaseResource;

class UserResource extends UserBaseResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */

    public function toArrayFilter($data = null)
    {
        return parent::toArrayFilter($data); // TODO: Change the autogenerated stub
    }
}
